---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  variables:
    gcloud_project: <%= ENV['GCLOUD_PROJECT'] %>

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    -
      name: default
      backend: gcp
      controls:
        - instance

platforms:
  - name: gcp

suites:
  -
    name: kt_suite
